### ISSUE TITLE
Plugin fail to load

### ISSUE THREAD

**Issue by AFaustini** [Garulf/Epic-Games-Store-Launcher#6]
[2023-05-23.txt](https://github.com/Garulf/Epic-Games-Store-Launcher/files/11547421/2023-05-23.txt)

Flow Launcher version: 1.15.0
OS Version: 22621.1702
IntPtr Length: 8
x64: True

Python Path: D:\Programas\FlowLauncher\app-1.15.0\UserData\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe
Node Path: D:\Programas\FlowLauncher\app-1.15.0\UserData\Environments\Node.js\Node-v16.18.0\node-v16.18.0-win-x64\node.exe
Date: 05/23/2023 15:50:06
Exception:
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Flow.Launcher.ReportWindow.SetException(Exception exception) in C:\projects\flow-launcher\Flow.Launcher\ReportWindow.xaml.cs:line 44
   at Flow.Launcher.ReportWindow..ctor(Exception exception) in C:\projects\flow-launcher\Flow.Launcher\ReportWindow.xaml.cs:line 23
   at Flow.Launcher.Helper.ErrorReporting.Report(Exception e) in C:\projects\flow-launcher\Flow.Launcher\Helper\ErrorReporting.cs:line 15
   at Flow.Launcher.Helper.ErrorReporting.DispatcherUnhandledException(Object sender, DispatcherUnhandledExceptionEventArgs e) in C:\projects\flow-launcher\Flow.Launcher\Helper\ErrorReporting.cs:line 28
   at System.Windows.Threading.Dispatcher.CatchException(Exception e)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by AFaustini** [comment]
When i manually remove all plugin folders and reinstall the plugin, works again
